export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_DRAWER_BOOLEAN = 'SET_DRAWER_BOOLEAN';
export const SET_ADMIN_DATA = 'SET_ADMIN_DATA';
export const SET_PRODUCTS_INFO = 'SET_PRODUCTS_INFO';
export const SET_PRODUCTS_SAVE_INFO = 'SET_PRODUCTS_SAVE_INFO';
export const SET_CUSTOMER_DATA = 'SET_CUSTOMER_DATA';




