export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_NOT_FOUND = 'SET_CURRENT_USER_NOT_FOUND';
export const SET_CURRENT_USER_EXIST = 'SET_CURRENT_USER_EXIST';
export const SET_REFRESH_STORETRANSECTION = 'SET_REFRESH_STORETRANSECTION';
export const SET_USERS_LIST = 'SET_USERS_LIST';
export const CREATE_USER = 'CREATE_USER';
export const SET_ROLE_LIST = 'SET_ROLE_LIST';
export const SET_PROJECTS_INFO = 'SET_PROJECTS_INFO';
export const SET_TASKS_INFO = 'SET_TASKS_INFO';
export const SET_FILTER_TASKS_INFO = 'SET_FILTER_TASKS_INFO';
export const SET_TASKS_INFO_BY_STATUS = 'SET_TASKS_INFO_BY_STATUS';
export const SET_TASKS_SCHEDULE = 'SET_TASKS_SCHEDULE';
export const SAVE_TASKS_LOG_BY_STATUS = 'SAVE_TASKS_LOG_BY_STATUS';
export const SET_NEW_TASKS = 'SET_NEW_TASKS';
export const SET_DRAWER_BOOLEAN = 'SET_DRAWER_BOOLEAN';
export const SET_TASKS_PROJECT_USERS = 'SET_TASKS_PROJECT_USERS';
export const SET_TASKS_REPORT_BY_USER = 'SET_TASKS_REPORT_BY_USER';
export const SET_USERS_ACTIVITY = 'SET_USERS_ACTIVITY';
export const SET_REPORT_BY_TASK = 'SET_REPORT_BY_TASK';



